[package]
name = "gem_version"
version = "1.0.0"
edition = "2021"
license = "BSD-3-Clause"
description = "Ruby's Gem::Version comparison logic in Rust"
keywords = ["Ruby", "version"]
repository = "https://github.com/schneems/gem_version"
documentation = "https://docs.rs/gem_version"
readme = "README.md"
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }

[dev-dependencies]
serde_json = "1.0"
